# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '6.x'
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
